# Generated by Django 3.2.9 on 2021-12-02 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('check_type', models.CharField(choices=[('kitchen', 'Kitchen'), ('client', 'Client')], max_length=7)),
                ('point_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('kitchen', 'Kitchen'), ('client', 'Client')], max_length=7)),
                ('order', models.JSONField()),
                ('status', models.CharField(choices=[('new', 'New'), ('rendered', 'Rendered'), ('printed', 'Printed')], max_length=8)),
                ('pdf_file', models.FileField(upload_to='')),
                ('printer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheque_generator.printer')),
            ],
        ),
    ]
