# Generated by Django 3.2.9 on 2021-12-06 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheque_generator', '0002_alter_check_pdf_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='check',
            unique_together={('order', 'printer_id')},
        ),
    ]
